export default [
    {
        name: "jetson",
        battery: 100,
        altitude: 0,
        relative_altitude: 0,
        latitude: 0,
        longitude: 0,
        speed: 0,
        lora_state: false,
        rpi_state: false,
    },
    {
        name: "red",
        battery: 100,
        altitude: 0,
        relative_altitude: 0,
        latitude: 0,
        longitude: 0,
        speed: 0,
        lora_state: false,
        rpi_state: false,
    },
    {
        name: "blue",
        battery: 100,
        altitude: 0,
        relative_altitude: 0,
        latitude: 0,
        longitude: 0,
        speed: 0,
        lora_state: false,
        rpi_state: false,
    },
]